baseURL: "https://j-dsouza.github.io"
languageCode: "en-us"
title: "James D'Souza"
theme: "PaperMod"
params:
  homeInfoParams:
    Title: Hi there ðŸ’
    Content: >
      - I'm a Software Engineer / Data Scientist at [Ki Insurance](https://ki-insurance.com), working on systems to understand and manage risk on insurance policies.

      - I like doing fun things with data, and turning those into reliable and maintainable software.

  socialIcons: # optional
    - name: github
      url: "https://www.github.com/j-dsouza"
    - name: linkedin
      url: "https://www.linkedin.com/in/james-d-souza-9368a150/"
    - name: email
      url: "mailto:james.dsouza@outlook.com"
